spring.application.name=backend-core

# # Kết nối Database
# spring.datasource.url=jdbc:postgresql://localhost:5432/english_app
# spring.datasource.username=postgres
# spring.datasource.password=12345

# # Hibernate cấu hình tự tạo bảng
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# Kết nối Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/english_app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

# Hibernate cấu hình tự tạo bảng
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=englishapp_super_secret_key_2026_vku_danang
jwt.expiration=86400000

google.client-id=1012513516239-5pgqmm7k3okhk32rj8jbo5i6ikou48r3.apps.googleusercontent.com
