spring.application.name=backend-core

# Kết nối PostgreSQL trên Render
spring.datasource.url=jdbc:postgresql://dpg-dasfdk8473hc7382ht7g-a.singapore-postgres.render.com:5432/english_training?sslmode=require
spring.datasource.username=english_training_user
spring.datasource.password=ErZbFrPIE4XroHLaqkLvk5eaq5LhkOaE

# Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:englishapp_super_secret_key_2026_vku_danang}
jwt.expiration=86400000

# Google OAuth2
google.client-id=${GOOGLE_CLIENT_ID:1012513516239-5pgqmm7k3okhk32rj8jbo5i6ikou48r3.apps.googleusercontent.com}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dqqbvzmrr}
cloudinary.api-key=${CLOUDINARY_API_KEY:789644833813378}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:changeme}

# Multipart upload - tối đa 10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
